services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assignment_db
    ports:
      - "3306:3306"
    networks:
      - springboot-network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assignment_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - springboot-network

networks:
  springboot-network:

volumes:
  mysql_data:
