name: Deploy Spring Boot App to EC2 with Docker

on:
  push:
    branches:
      - master  # Trigger on push to master
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17 (Temurin)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -T 1C

      # Step 4: SSH to EC2 and deploy
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            if [ ! -d "springboot-app" ]; then
              git clone https://github.com/yourusername/yourrepo springboot-app
            fi
            cd springboot-app
            git pull origin master

            # Stop and remove old container
            sudo docker stop springboot-app || true
            sudo docker rm springboot-app || true

            # Remove old image
            sudo docker image rm springboot-app || true

            # Build and run new Docker container
            sudo docker build -t springboot-app .
            sudo docker run -d -p 8080:8080 --name springboot-app springboot-app

            # Optional: Clean up unused Docker resources
            sudo docker system prune -f

            echo "✅ Deployment complete."
