name: Deploy Spring Boot App to EC2 with Docker

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t springboot-app .

      - name: SSH to EC2 and Clone Repo, Build & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Navigate to the home directory and clone the repo if not already present
            cd ~
            if [ ! -d "springboot-app" ]; then
              git clone https://github.com/sakshijain2002/springbootassignment springboot-app
            fi
            
            cd springboot-app
            git pull origin master  # Pull the latest changes

            # Build the JAR (or Docker image) on EC2
            mvn clean package -DskipTests
            docker build -t springboot-app .

            # Run Docker Compose to deploy the application
            docker compose -f deploy.yml down || true
            docker compose -f deploy.yml up --build -d
