name: Deploy Spring Boot App on Self-Hosted Runner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Cache Maven Dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # Step 3: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Build the project with Maven (skip tests for speed)
      - name: Build with Maven
        run: mvn -B clean package -DskipTests -T 1C

      # Step 5: Stop and remove existing container (if running)
      - name: Stop existing container
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true

      # Step 6: Remove old Docker image (if any)
      - name: Remove old Docker image
        run: docker image rm springboot-app || true

      # Step 7: Build new Docker image
      - name: Build Docker image
        run: docker build -t springboot-app .

      # Step 8: Check Docker Info
      - name: Check Docker Info
        run: docker info

      # Step 9: List Docker Images (debugging step)
      - name: List Docker Images
        run: docker images

      # Step 10: Run Docker container with secrets passed as environment variables
      - name: Run Docker container
        run: |
            docker run -d \
              --name springboot-app \
              -e RDS_URL=${{ secrets.RDS_URL }} \
              -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
              -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              -p 8080:8080 \
              springboot-app
          
       

      # Step 11: Show container logs (for debugging)
      - name: Show Docker logs
        run: |
          echo "📦 Container logs (last 100 lines):"
          docker logs --tail 100 springboot-app

      # Step 12: Optional cleanup to save space
      - name: Cleanup Docker images
        run: docker image prune -f

      # Step 13: Final status
      - name: Done
        run: echo "✅ Deployment finished successfully on self-hosted runner"
