name: Deploy Spring Boot App to EC2 with Docker

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SSH to EC2 and Build & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Go to home and clone project if not exists
            cd ~
            if [ ! -d "springboot-app" ]; then
              git clone https://github.com/sakshijain2002/springbootassignment springboot-app
            fi

            cd springboot-app
            git pull origin master

            # Build Docker image
            docker build -t springboot-app .

            # Stop and remove old container
            docker stop springboot-app-container || true
            docker rm springboot-app-container || true

            # Run new container with environment variables
            docker run -d -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=${{ secrets.RDS_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              -e APP_SECRET=${{ secrets.APP_SECRET }} \
              --name springboot-app-container springboot-app
