name: Deploy Spring Boot App to EC2 with Docker

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t springboot-app .

      - name: Copy Docker image and files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/*.jar Dockerfile deploy.yml"  # Only copy necessary files
          target: "/home/ec2-user/springboot-app"


      - name: Run Docker Container on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            
            cd /home/ec2-user/springboot-app

            # Stop and remove any old containers if they exist
            docker stop springboot-app-container || true
            docker rm springboot-app-container || true

            # Run the new Docker container
            docker run -d -p 8080:8080 --name springboot-app-container springboot-app
