name: Deploy Spring Boot App on Self-Hosted Runner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Run directly on your self-hosted runner (e.g., EC2)

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -T 1C

      # Step 4: Stop and remove existing container
      - name: Stop existing container
        run: |
          docker stop springboot-app || true
          docker rm springboot-app || true

      # Step 5: Remove old image
      - name: Remove old Docker image
        run: docker image rm springboot-app || true

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t springboot-app .

      # Step 7: Run Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name springboot-app springboot-app

      # Step 8: (Optional) Prune Docker system
      - name: Cleanup Docker
        run: docker system prune -f

      - name: Done
        run: echo "✅ Deployment finished on self-hosted runner"
