name: Deploy to EC2 and MySQL Container

on:
  push:
    branches:
      - master  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}  # Using the secret for the private key

      - name: Set up SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} <<EOF
            echo "Connected to EC2"
          
            # Clone repository if not already present
            if [ ! -d "springboot-assignment" ]; then
              git clone https://github.com/sakshijain2002/springbootassignment springboot-assignment
            fi

            cd springboot-assignment
            git pull origin master

            echo "Running Maven build..."
            mvn clean package -DskipTests

            echo "Starting MySQL container..."
            docker rm -f mysql-container || true  # Remove any existing container
            docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=assignment_db -e MYSQL_USER=root -e MYSQL_PASSWORD=root -p 3306:3306 -d mysql:latest

            echo "Restarting Spring Boot Docker container..."
            docker rm -f springboot-app || true
            docker-compose down || true
            docker-compose up -d

            echo "Deployment finished"
          EOF
