name: Deploy to EC2 and RDS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Ensure you're using the correct Java version

      - name: Build with Maven
        run: mvn package -DskipTests  # Use mvn instead of ./mvnw

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}  # Using the secret for the private key

      - name: Set up SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/springboot-assignment  # Adjust to your project directory
            git pull origin main  # Pull the latest code
            docker-compose down  # Stop the running container if any
            docker-compose up -d  # Rebuild and start the container
          
